name: Deploy ElMayordomo2025 to Vercel

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Deploy to Vercel
              run: |
                  vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

            - name: Validate Deployment
              run: |
                  echo "🎭 ElMayordomo2025 Avatar System Deployed Successfully!"
                  echo "🎯 Issue #20 Resolution Confirmed"
                  echo "✅ NO MAS PAYASADAS - System Operational!"
